"""Type stub for the build-time-generated _engine_rlocation module.

The .py file is generated by //src/hivemind:_engine_rlocation at build
time and lives in bazel-bin/, not the source tree. This stub lets
both Bazel-driven and uv-driven mypy resolve the import the same way
without an inline `# type: ignore`.
"""

ENGINE_RLOCATION: str
