"""Auto-generated by //src/hivemind:_engine_rlocation. Do not edit.

ENGINE_RLOCATION is the runfiles-manifest key for //:engine, derived at
build time from $(rlocationpath //:engine). This file is regenerated
whenever the engine's bzlmod canonicalization changes (extension rename,
repo rename, etc.) — there are no hardcoded canonical names in source.
"""

ENGINE_RLOCATION = "__ENGINE_RLOCATION__"
