"""Protocol interfaces for hivemind services.

These define the boundaries between use cases and infrastructure.
Currently implemented directly in core.py; will be extracted into
separate adapter modules as the codebase grows.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from pathlib import Path

# --- Config Repositories ---


class ProjectConfigRepository(Protocol):
    """Interface for shared project config (hivemind.json)."""

    def load_providers(self) -> dict[str, dict]: ...
    def load_repos(self) -> dict[str, dict]: ...
    def save_repos(self, repos: dict[str, dict]) -> None: ...
    def load(self) -> dict: ...
    def save(self, data: dict) -> None: ...


class UserConfigRepository(Protocol):
    """Interface for local user config (config.json)."""

    def load(self) -> dict: ...
    def save(self, config: dict) -> None: ...
    def get_enabled_experts(self) -> list[str]: ...
    def get_active_provider(self) -> str | None: ...
    def load_teams(self) -> dict: ...
    def save_teams(self, teams: dict) -> None: ...


# --- Infrastructure Services ---


class GitService(Protocol):
    """Interface for git operations."""

    def clone(
        self, remote: str, target: Path, *, commit: str = "", ref_name: str = "", silent: bool = False
    ) -> bool: ...
    def fetch(self, repo_dir: Path) -> None: ...
    def checkout(self, repo_dir: Path, commit: str) -> None: ...
    def resolve_latest_commit(self, repo_dir: Path) -> str | None: ...
    def rev_parse(self, repo_dir: Path, ref: str) -> str | None: ...


class ExpertFileStore(Protocol):
    """Interface for expert directory and version management."""

    def get_expert_dir(self, name: str) -> Path: ...
    def get_head_commit(self, expert_dir: Path) -> str | None: ...
    def count_versions(self, expert_dir: Path) -> int: ...
    def list_expert_names(self) -> list[str]: ...
    def update_head_symlink(self, expert_dir: Path, commit: str) -> None: ...


# --- Provider Service (= existing Provider ABC from providers.py) ---
# The Provider abstract base class in providers.py already serves as
# the ProviderService port. No additional protocol needed here.
