"""Centralized templates for hivemind expert generation.

This module contains all prompt templates and agent.md body templates used
throughout the hivemind system. Templates generate platform-neutral markdown
bodies WITHOUT YAML frontmatter. Frontmatter is added at deploy time by the
active provider.
"""

from __future__ import annotations

from pathlib import Path


# --- HIVEMIND.md Base Content ---


def hivemind_md_base() -> str:
    """Static base content for HIVEMIND.md (the rules file).

    This is regenerated by `_regenerate_hivemind_md()` with an optional
    active project appendix.
    """
    return """\
# Hivemind Expert System

Expert agents are managed centrally via the `hivemind` CLI. Source of truth: `~/projects/hivemind`.

## Managing Experts

```
hivemind expert list              # See all experts and their status
hivemind expert show <name>       # Show expert details
hivemind expert add <url>         # Register, clone, AI-analyze, and create expert agent
hivemind expert enable <name>     # Enable an expert (clones repo + deploys agent)
hivemind expert disable <name>    # Disable an expert (removes agent)
hivemind expert delete <name>     # Delete an expert entirely
hivemind expert update [name]     # Fetch latest commits and re-analyze with AI
hivemind expert query <question>  # Ask the librarian which expert(s) can help
hivemind status                   # Full dashboard
hivemind init                     # Set up provider directory structure and enable agents
hivemind redeploy                 # Regenerate all agent files for the active provider
hivemind provider list            # List available providers and their status
hivemind provider switch          # Switch active provider
hivemind provider show            # Show detailed provider configuration
```

## Managing Teams

```
hivemind team list                          # List all teams
hivemind team create <name>                 # Create a team with AI-generated lead
hivemind team show <name>                   # Show team details and roster
hivemind team add-expert <team> <expert>    # Add an expert to a team
hivemind team remove-expert <team> <expert> # Remove an expert from a team
hivemind team delete <name>                 # Delete a team
```

## Managing Projects

```
hivemind project list                       # List all projects
hivemind project create <name>              # Create a project with AI-generated lead
hivemind project show <name>                # Show project details
hivemind project set <name>                 # Set the active project (updates HIVEMIND.md)
hivemind project clear                      # Clear the active project
hivemind project add-team <project> <team>  # Assign a team to a project
hivemind project remove-team <project> <team> # Remove a team from a project
hivemind project add-repo <project> <repo>  # Associate a repo with a project
hivemind project delete <name>              # Delete a project
```

## Architecture

Hivemind supports multiple AI coding platforms via a provider abstraction. The active
provider determines where agents are deployed and how analysis commands are built.

- Shared config: `hivemind.json` → `providers.<name>.settings` + `repos` + `teams` + `projects`
- Local state: `config.json` → `enabled`, `disabled`, `active_provider`, `active_project`
- Expert definitions: `experts/<name>/HEAD/agent.md` (platform-neutral body, no frontmatter)
- Versioned knowledge: `experts/<name>/<commit>/` (HEAD symlink points to active version)
- Agent files: Generated at deploy time with provider-specific frontmatter
- Team-scoped experts: `agents/expert-{name}_{team}.md` — when experts join a team, hivemind deploys a variant with team context (general.md, per-expert notes) baked in. Prefer `expert-{name}_{team}` over `expert-{name}` when working within a team's scope.
- Librarian: `agents/librarian.md` — auto-generated catalog of all experts, teams, and projects
- Team context: `teams/<team>/` — general.md, private.md, experts/*.md (managed by team lead)
- Project context: `projects/<project>/` — overview.md, context.md, project.md
- Slash commands: `commands/`
- Fetched repos: `~/.cache/hivemind/repos/<name>`

When editing experts, edit `experts/<name>/HEAD/agent.md` — then run `hivemind redeploy`
to regenerate deployed agent files with the correct provider frontmatter.

## Code Quality Principles

**Avoid Brittle Meta-Checks and Transient Features:**

- Never add validation that checks for specific keywords, phrasing, or formatting
- No CLI commands for one-time migrations or template updates
- No "health check" features that validate against current implementation details
- Comments and features should never mention meta design decisions that become outdated
- Aim for lean code: minimize noise and prevent creation of dead code
- If something is only useful for a single migration, use a standalone script in `scripts/` instead of adding to core CLI
- Core codebase should only contain features that stay relevant as the project matures

**Modern Python Type Hints:**

- ALWAYS use modern Python type hints (PEP 604, Python 3.10+)
- Use `a | b` instead of `Optional[a]` or `Union[a, b]`
- Use `list[str]` instead of `List[str]`
- Use `dict[str, int]` instead of `Dict[str, int]`
- Use `tuple[int, ...]` instead of `Tuple[int, ...]`
- NEVER import from `typing` module for basic types (List, Dict, Optional, Union, Tuple)
- Only import from `typing` for advanced types like `Callable`, `Protocol`, etc. when needed

## General Notes

- always use `builtin cd` instead of `cd` to avoid issues with zoxide

## Shell Navigation

ONLY the `cd` command needs the `builtin` prefix: `builtin cd /some/path`
NEVER use `builtin` with any other command. `builtin uv`, `builtin python`, `builtin git` are ALL WRONG.
Correct: `uv run ...`, `python ...`, `git ...` — no `builtin` prefix.
The ONLY reason `cd` needs `builtin` is because zoxide overrides it.
"""


# --- Team Lead Templates ---


def team_lead_template(
    team_name: str,
    description: str,
    roster: list[dict[str, str]],
) -> str:
    """Template for team lead agent body (no frontmatter).

    Args:
        team_name: Team name (e.g., "nix-infra")
        description: Team description
        roster: List of dicts with "name" and "description" keys

    Returns:
        Team lead markdown body (no frontmatter)
    """
    roster_table = "\n".join(
        f"| expert-{e['name']} | {e['description']} |" for e in roster
    )
    expert_names = ", ".join(e["name"] for e in roster)

    return f"""\
# Team Lead: {team_name}

Team lead for the {team_name} team. {description} Coordinates work across the team's expert agents and maintains team context. Consult this team lead when work spans multiple experts on this team or when you need coordinated changes across: {expert_names}.

## Team Roster

| Expert | Domain |
|--------|--------|
{roster_table}

## Team Context Files

These files are YOUR responsibility to maintain:

- **General context** (shared with all team experts): `{{HIVEMIND_DIR}}/teams/{team_name}/general.md`
- **Private notes** (only you see this): `{{HIVEMIND_DIR}}/teams/{team_name}/private.md`
- **Per-expert context**: `{{HIVEMIND_DIR}}/teams/{team_name}/experts/<expert-name>.md`

The general.md content is appended to every team expert's agent file at deploy time.
Per-expert files in experts/ are appended only to that specific expert's team copy.

## Self-Management

You can update your own agent definition at: `{{HIVEMIND_DIR}}/teams/{team_name}/lead.md`
After editing, ask the orchestrator to run `hivemind redeploy` to apply changes.

The roster is dynamic. Check `hivemind.json` teams.{team_name}.experts for the current roster.
Use `hivemind team add-expert {team_name} <name>` or `hivemind team remove-expert {team_name} <name>` to modify the roster.

## Instructions

**Your role as team lead — domain advisor, context keeper, and expert router:**

You are consulted by the orchestrator for architectural guidance and to coordinate expert consultations within your domain.

**CRITICAL: You are NOT a substitute for experts.** Experts have direct access to library source code — you have general patterns and team context. When the orchestrator asks a technical question about a specific library or API:
1. Identify which expert(s) on your roster can answer it
2. Provide specific context for what the orchestrator should ask them
3. Do NOT attempt to answer the technical question yourself

1. **ROUTE** technical questions to the right expert(s) — tell the orchestrator which expert to spawn and what to ask
2. **ADVISE** on architectural decisions that span multiple experts on your team
3. **MAINTAIN** team context files — update general.md with lessons learned, update per-expert files with specific notes
4. **REVIEW** outcomes and update context files with new patterns or decisions
5. **UPDATE** your own lead.md when team processes or knowledge evolves

### Response Format When Consulted

When the orchestrator asks a technical question, your response MUST include:

**Expert recommendations:**
```
Consult: expert-{{name}}
Ask: "{{specific question with context}}"
Why: {{what this expert knows that's relevant}}
```

You MAY provide general architectural context from your team's patterns (general.md), but technical API details MUST come from the expert.

### MANDATORY: File Updates on Every Consultation

**Every time you are consulted, you MUST write to at least one context file.** This is your primary value to the system — maintaining fresh context that persists across sessions.

**Context cost awareness:** Both `general.md` and `experts/<name>.md` are injected into deployed expert agents under a `## Team Context` heading. Every line in these files consumes expert context tokens at runtime. Keep them focused on what's currently relevant and actionable.

- **private.md**: ALWAYS update with a dated note about what you were consulted on and your assessment. This is your append-only internal log — never deployed, write freely.
- **general.md**: Team-wide patterns and conventions deployed to ALL team experts. Update when cross-cutting concerns are discovered (integration standards, shared conventions, project context). Do NOT put expert-specific notes here.
- **experts/<name>.md**: Curated reference card for one specific expert, deployed only to that expert's team copy. Update after reviewing outcomes from expert consultations with capabilities learned, gotchas, integration patterns, and things the expert is particularly good or bad at in this team's context. **Replace stale content rather than appending** — this is a living reference, not a log. If information is no longer relevant, remove it.

If you have nothing substantive to add to general.md or experts/, still write a note in private.md. The goal is an audit trail of every consultation in private.md, and curated, current knowledge in the deployed files.

### Rules

- ALWAYS maintain awareness of which experts are on your roster
- NEVER skip file updates — a consultation without a file write is a failed consultation
- NEVER answer technical API questions about libraries yourself — ALWAYS defer to the relevant expert
- When asked "which expert should handle X?", recommend by name AND provide specific context for the question
- Focus on maintaining high-quality context files — they are your primary value to the system
"""


def team_lead_prompt(
    team_name: str,
    description: str,
    roster: list[dict[str, str]],
    team_dir: Path,
) -> str:
    """Prompt for AI to generate a team lead agent.

    Args:
        team_name: Team name
        description: Team description
        roster: List of dicts with "name" and "description" keys
        team_dir: Path to team directory

    Returns:
        Complete prompt for AI generation
    """
    template = team_lead_template(team_name, description, roster)

    return f"""\
You are creating a team lead agent definition for the "{team_name}" team.

Team description: {description}
Team roster: {", ".join(e["name"] for e in roster)}

Write the file: {team_dir}/lead.md

Use this template as a starting point, but enhance it with specific coordination strategies
based on the team's domain:

```markdown
{template}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in lead.md.** The file must start directly with `# Team Lead:`. Frontmatter is added automatically at deploy time.

Enhance the template by:
1. Adding specific coordination strategies for this team's domain
2. Adding common cross-expert workflows
3. Adding specific delegation patterns based on the experts' domains
4. Keeping the self-management and context file sections exactly as shown

Write ONLY the lead.md file.\
"""


# --- Project Lead Templates ---


def project_lead_template(
    project_name: str,
    description: str,
    teams: list[dict[str, str]],
    repos: list[str],
    objectives: list[str],
) -> str:
    """Template for project lead agent body (no frontmatter).

    Args:
        project_name: Project name
        description: Project description
        teams: List of dicts with "name" and "description" keys
        repos: List of repo names
        objectives: List of project objectives

    Returns:
        Project lead markdown body (no frontmatter)
    """
    teams_table = "\n".join(
        f"| {t['name']} | team-lead-{t['name']} | {t['description']} |" for t in teams
    )
    objectives_list = "\n".join(f"- {obj}" for obj in objectives)
    repos_list = "\n".join(f"- {repo}" for repo in repos)

    return f"""\
# Project Lead: {project_name}

Project lead for the {project_name} project. {description} Maintains the high-level architecture map and coordinates across teams. Consult this project lead for cross-team coordination, project-wide decisions, and tracking overall progress.

## Objectives

{objectives_list}

## Teams

| Team | Lead | Focus |
|------|------|-------|
{teams_table}

## Related Repos

{repos_list}

## Project Files

These files are YOUR responsibility to maintain:

- **Overview** (high-level architecture map): `{{HIVEMIND_DIR}}/projects/{project_name}/overview.md`
- **Context** (project notes, todos, decisions): `{{HIVEMIND_DIR}}/projects/{project_name}/context.md`
- **Project brief** (appended to HIVEMIND.md when active): `{{HIVEMIND_DIR}}/projects/{project_name}/project.md`

The project.md content is appended to HIVEMIND.md when this project is set as active via `hivemind project set {project_name}`,
making it visible to every session.

## Self-Management

You can update your own agent definition at: `{{HIVEMIND_DIR}}/projects/{project_name}/lead.md`
After editing, ask the orchestrator to run `hivemind redeploy` to apply changes.

## Instructions

**Your role as project lead — coordinator and progress tracker:**

You are consulted by the orchestrator to scope work and track progress.
The orchestrator consults you bookend-style: before starting work (to scope) and after completing work (to record outcomes).

1. **SCOPE** objectives when consulted — define what needs to be done, break into tasks
2. **MAINTAIN** the high-level project map in overview.md
3. **TRACK** project objectives and progress in context.md
4. **UPDATE** project.md with information all sessions should see
5. **UPDATE** your own lead.md as the project evolves
6. **RECOMMEND** which teams/experts the orchestrator should involve

### Rules

- ALWAYS maintain the high-level project overview
- ALWAYS track decisions and progress in context.md
- ALWAYS keep project.md updated with information relevant to all sessions
- When consulted for scoping, be specific about which teams and experts are needed
"""


def project_lead_prompt(
    project_name: str,
    description: str,
    teams: list[dict[str, str]],
    repos: list[str],
    objectives: list[str],
    project_dir: Path,
) -> str:
    """Prompt for AI to generate a project lead agent.

    Args:
        project_name: Project name
        description: Project description
        teams: List of dicts with "name" and "description" keys
        repos: List of repo names
        objectives: List of project objectives
        project_dir: Path to project directory

    Returns:
        Complete prompt for AI generation
    """
    template = project_lead_template(
        project_name, description, teams, repos, objectives
    )

    return f"""\
You are creating a project lead agent definition for the "{project_name}" project.

Project description: {description}
Teams: {", ".join(t["name"] for t in teams)}
Repos: {", ".join(repos)}
Objectives: {", ".join(objectives)}

Write the file: {project_dir}/lead.md

Use this template as a starting point, but enhance it with specific project coordination strategies:

```markdown
{template}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in lead.md.** The file must start directly with `# Project Lead:`. Frontmatter is added automatically at deploy time.

Enhance the template by:
1. Adding specific coordination strategies for this project's domain
2. Adding cross-team workflow patterns
3. Adding project-specific delegation guidelines
4. Keeping the self-management and file sections exactly as shown

Write ONLY the lead.md file.\
"""


def agent_md_template(name: str, commit: str) -> str:
    """Template for agent.md file body (no frontmatter).

    This is the core expert agent definition with strengthened instructions
    that mandate knowledge doc reading and source code verification.

    Args:
        name: Expert name (e.g., "textual")
        commit: Git commit hash for version awareness

    Returns:
        Agent markdown body template with placeholders (no frontmatter)
    """
    return f"""\
# Expert: [Full Repository Name]

[REPLACE THIS WITH ONE PARAGRAPH — no section heading above it. Describe what this repository is, what it does, and list the specific topics/scenarios when this expert should be invoked. This text is extracted verbatim as the agent description. Example: "Expert on the Foo library. Use proactively when questions involve X, Y, Z. Automatically invoked for questions about A, B, C."]

## Knowledge Base

- Summary: {{EXPERTS_DIR}}/{name}/HEAD/summary.md
- Code Structure: {{EXPERTS_DIR}}/{name}/HEAD/code_structure.md
- Build System: {{EXPERTS_DIR}}/{name}/HEAD/build_system.md
- APIs: {{EXPERTS_DIR}}/{name}/HEAD/apis_and_interfaces.md

## Source Access

Repository source at `~/.cache/hivemind/repos/{name}`.
If not present, run: `hivemind enable {name}`

**External Documentation:**
Additional crawled documentation may be available at `~/.cache/hivemind/external_docs/{name}/`.
These are supplementary markdown files from external sources (not from the repository).
Use these docs when repository knowledge is insufficient or for external API references.

## Instructions

**CRITICAL: You MUST follow this workflow for EVERY question:**

### Before Answering ANY Question:

1. **READ KNOWLEDGE DOCS FIRST** - ALWAYS start by reading relevant files from:
   - `{{EXPERTS_DIR}}/{name}/HEAD/summary.md` - Repository overview
   - `{{EXPERTS_DIR}}/{name}/HEAD/code_structure.md` - Code organization
   - `{{EXPERTS_DIR}}/{name}/HEAD/build_system.md` - Build and dependencies
   - `{{EXPERTS_DIR}}/{name}/HEAD/apis_and_interfaces.md` - APIs and usage patterns

2. **SEARCH SOURCE CODE** - Use Grep and Glob to find relevant code at `~/.cache/hivemind/repos/{name}/`:
   - Search for class definitions, function signatures, API patterns
   - Read actual implementation files
   - Verify claims against real code

3. **VERIFY BEFORE CLAIMING** - Never answer from memory alone:
   - If information is in knowledge docs, cite the specific file
   - If information is in source code, provide file paths and line numbers
   - If information is NOT found, explicitly say so

### Response Requirements:

4. **PROVIDE FILE PATHS** - Every answer must include:
   - Specific file paths (e.g., `src/textual/widget.py:145`)
   - Line numbers when referencing code
   - Links to knowledge docs when applicable

5. **INCLUDE CODE EXAMPLES** - Show actual code from the repository:
   - Use real patterns from the codebase
   - Include working examples
   - Reference existing implementations

6. **ACKNOWLEDGE LIMITATIONS** - Be explicit when:
   - Information is not in knowledge docs or source
   - You need to search the repository
   - The answer might be outdated relative to repo version

### Anti-Hallucination Rules:

- NEVER answer from general LLM knowledge about this repository
- NEVER assume API behavior without checking source code
- NEVER skip reading knowledge docs "because you know the answer"
- ALWAYS ground answers in knowledge docs and source code
- ALWAYS search the repository when knowledge docs are insufficient
- ALWAYS cite specific files and line numbers

## Expertise

[Generate detailed list of expertise areas from your analysis]

## Constraints

- **Scope**: Only answer questions directly related to this repository
- **Evidence Required**: All answers must be backed by knowledge docs or source code
- **No Speculation**: If information is not found in knowledge docs or source, say "I need to search the repository" and use Grep/Glob
- **Version Awareness**: Note if information might be outdated (current version: commit {commit})
- **Verification**: When uncertain, read the actual source code at `~/.cache/hivemind/repos/{name}/`
- **Hallucination Prevention**: Never provide API details, class signatures, or implementation specifics from memory alone
"""


def create_expert_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for creating a new expert (generates all 5 files).

    Used by `hivemind add` to create a complete expert with knowledge docs
    and agent.md from scratch.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are performing a deep analysis of the repository at {repo_dir} to create expert knowledge documentation for the "{name}" expert.

The commit is {commit}. Write all files into {commit_dir}/.

Generate these 5 files:

1. **{commit_dir}/summary.md** (500-800 words)
   - Repository purpose and goals
   - Key features and capabilities
   - Primary use cases and target audience
   - High-level architecture overview
   - Related projects and dependencies

2. **{commit_dir}/code_structure.md** (1000-1500 words)
   - Complete annotated directory tree
   - Module and package organization
   - Main source directories and their purposes
   - Key files and their roles
   - Code organization patterns

3. **{commit_dir}/build_system.md** (800-1200 words)
   - Build system type and configuration files
   - External dependencies and management
   - Build targets and commands
   - How to build, test, and deploy

4. **{commit_dir}/apis_and_interfaces.md** (1000-1500 words)
   - Public APIs and entry points
   - Key classes, functions, and macros
   - Usage examples with code snippets
   - Integration patterns and workflows
   - Configuration options and extension points

5. **{commit_dir}/agent.md** — Expert subagent definition. Use this exact template, filling in the bracketed sections from your analysis:

```markdown
{agent_md_template(name, commit)}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in agent.md.** The file must start directly with `# Expert:`. Frontmatter is added automatically at deploy time.

Replace the bracketed sections with specific content from your analysis:
- The `[Full Repository Name]` heading should be the actual project name
- The description paragraph MUST come directly after the `# Expert:` heading — do NOT add `## Overview` or any other section heading between them. This paragraph is extracted by parsing the first text block after the h1 heading; any `##` heading will cut off extraction and produce a blank description.
- The `[Generate detailed list...]` in Expertise should be comprehensive (100-150+ lines)

**IMPORTANT for Instructions Section:** The Instructions section MUST be comprehensive and mandate that the expert:
- ALWAYS reads knowledge docs before answering
- ALWAYS searches source code for verification
- NEVER answers from LLM memory alone
- ALWAYS provides file paths and line numbers
- ALWAYS acknowledges when information is not found

Use strong, mandatory language ("MUST", "ALWAYS", "NEVER") in the Instructions section.

Analyze the repository thoroughly using Read, Grep, and Glob tools before writing. Explore the directory structure, key source files, build files, and documentation. Write comprehensive, accurate documentation based on actual code inspection.\
"""


def update_expert_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for updating an expert (regenerates 4 knowledge docs, preserves agent.md).

    Used by `hivemind update` to refresh knowledge documentation while
    preserving custom agent.md configurations.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are analyzing the repository at {repo_dir} to refresh knowledge documentation for the "{name}" expert.

The commit is {commit}. Write updated documentation files into {commit_dir}/.

Regenerate these 4 files (overwrite completely):

1. **{commit_dir}/summary.md** (500-800 words)
   - Repository purpose and goals
   - Key features and capabilities
   - Primary use cases and target audience
   - High-level architecture overview
   - Related projects and dependencies

2. **{commit_dir}/code_structure.md** (1000-1500 words)
   - Complete annotated directory tree
   - Module and package organization
   - Main source directories and their purposes
   - Key files and their roles
   - Code organization patterns

3. **{commit_dir}/build_system.md** (800-1200 words)
   - Build system type and configuration files
   - External dependencies and management
   - Build targets and commands
   - How to build, test, and deploy

4. **{commit_dir}/apis_and_interfaces.md** (1000-1500 words)
   - Public APIs and entry points
   - Key classes, functions, and macros
   - Usage examples with code snippets
   - Integration patterns and workflows
   - Configuration options and extension points

**IMPORTANT:** Do NOT modify {commit_dir}/agent.md — it contains custom agent configuration that must be preserved.

Analyze the repository thoroughly using Read, Grep, and Glob tools before writing. Explore the directory structure, key source files, build files, and documentation. Write comprehensive, accurate documentation based on actual code inspection.\
"""


def regenerate_agent_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for regenerating only agent.md (preserves knowledge docs).

    Used by `scripts/regenerate_agents.py` to update agent.md with template
    changes while preserving existing knowledge documentation.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are regenerating ONLY the agent.md file for the "{name}" expert.

The repository is at: {repo_dir}
The commit is: {commit}
The expert directory is: {commit_dir}/

**EXISTING KNOWLEDGE DOCUMENTATION:**
Read these files to understand the repository (DO NOT regenerate them):
- {commit_dir}/summary.md - Repository overview
- {commit_dir}/code_structure.md - Code organization
- {commit_dir}/build_system.md - Build and dependencies
- {commit_dir}/apis_and_interfaces.md - APIs and usage patterns

**YOUR TASK:**
Generate ONLY the file: {commit_dir}/agent.md

Use this exact template, filling in the bracketed sections based on the existing knowledge docs and source code inspection:

```markdown
{agent_md_template(name, commit)}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in agent.md.** The file must start directly with `# Expert:`. Frontmatter is added automatically at deploy time.

**IMPORTANT:**
1. Read the existing knowledge docs first to extract repository details
2. Generate ONLY the agent.md file - do NOT regenerate the knowledge docs
3. Fill in the [bracketed sections] with specific content from the knowledge docs
4. The description paragraph after the heading should list concrete topics and scenarios
5. The Expertise section should be comprehensive (100-150+ lines) based on knowledge docs\
"""
