"""Centralized templates for hivemind expert generation.

This module contains all prompt templates and agent.md body templates used
throughout the hivemind system. Templates generate platform-neutral markdown
bodies WITHOUT YAML frontmatter. Frontmatter is added at deploy time by the
active provider.
"""

from __future__ import annotations

from pathlib import Path


# --- HIVEMIND.md Base Content ---


def hivemind_md_base() -> str:
    """Static base content for HIVEMIND.md (the rules file).

    This is regenerated by `_regenerate_hivemind_md()` with provider-specific
    instructions appended.
    """
    return """\
# Hivemind Expert System

Expert agents are managed centrally via the `hivemind` CLI. Source of truth: `~/projects/hivemind`.

## Commands

```
hivemind expert list              # See all experts and their status
hivemind expert show <name>       # Show expert details
hivemind expert add <url>         # Register, clone, AI-analyze, and create expert agent
hivemind expert enable <name>     # Enable an expert (clones repo + deploys agent)
hivemind expert disable <name>    # Disable an expert (removes agent)
hivemind expert delete <name>     # Delete an expert entirely
hivemind expert update [name]     # Fetch latest commits and re-analyze with AI
hivemind expert query <question>  # Ask the librarian which expert(s) can help
hivemind team list                # List all teams
hivemind team create <name>       # Create a team with AI-generated lead
hivemind team show <name>         # Show team details and roster
hivemind team add-expert <t> <e>  # Add an expert to a team
hivemind team remove-expert <t> <e> # Remove an expert from a team
hivemind team delete <name>       # Delete a team
hivemind status                   # Full dashboard
hivemind redeploy                 # Regenerate all agent files
hivemind init                     # Set up provider directory structure
```

## Architecture

- Expert definitions: `experts/<name>/HEAD/agent.md` (platform-neutral, no frontmatter)
- Versioned knowledge: `experts/<name>/<commit>/` (HEAD symlink → active version)
- Deployed agents: `agents/` — generated at deploy time with provider-specific frontmatter
- Librarian: `agents/librarian.md` — auto-generated catalog of all experts and teams
- Team leads: `teams/<team>/lead.md` → deployed as `agents/team-lead-<team>.md`
- Expert notes: `teams/<team>/expert-<name>/notes.md` — per-expert consultation journal
- Fetched repos: `~/.cache/hivemind/repos/<name>`

## Workflow

You (main) handle all implementation directly. Subagents are for domain research only — they cannot spawn other agents.

### When you need domain expertise:

1. **Consult the team lead** — spawn `team-lead-{team}` to get routing advice. The team lead knows each expert's strengths and recent consultation history (via notes.md files). It will recommend which expert(s) to call and what to ask.

2. **Spawn experts in parallel** — call the recommended experts with specific questions. Include which team they're part of so they can update their notes. Experts read their knowledge docs and source code, then report findings.

3. **Experts update their notes** — each expert writes to `teams/{team}/expert-{name}/notes.md` with what was asked and what they found. This builds institutional memory across sessions.

### When you don't know which team or expert to use:

Spawn the **librarian** (`librarian`) — it knows every expert and team and will recommend who to consult.

### Key principles:

- **You do the implementation** — read code, write code, run commands. Subagents research and advise.
- **Subagents cannot spawn other agents** — only you can. Depth is limited to 1.
- **Maximize parallel expert calls** — if you need input from multiple experts, spawn them all at once.
- **Experts are grounded in source code** — they have access to cloned repos and structured knowledge docs. Trust their findings over general knowledge.
"""


# --- Team Lead Templates ---


def team_lead_template(
    team_name: str,
    description: str,
    expert_sections: str,
) -> str:
    """Template for team lead agent body (no frontmatter).

    The roster list is NOT included here — it's injected at deploy time
    from config.json so it's always current.

    Args:
        team_name: Team name (e.g., "backend")
        description: Team description
        expert_sections: Pre-generated ## expert-{name} sections concatenated

    Returns:
        Team lead markdown body (no frontmatter)
    """
    return f"""\
# Team Lead: {team_name}

{description}

{expert_sections}

## Expert Notes

Each expert maintains a consultation log at `{{HIVEMIND_DIR}}/teams/{team_name}/expert-<name>/notes.md`.
Read these files before routing — they contain recent consultation history and findings for each expert.

## Instructions

You are a router and domain advisor. When the orchestrator asks a question:

1. **Read** relevant expert notes to understand recent context
2. **Recommend** which expert(s) to consult and what to ask them
3. **Advise** on architectural decisions that span multiple experts

You are NOT a substitute for experts. Experts have direct access to source code — you have the big picture. Never answer technical API questions yourself.
"""


def expert_section_prompt(
    expert_name: str,
    team_name: str,
    expert_dir: Path,
) -> str:
    """Prompt for AI to generate a single ## expert-{name} section.

    The AI reads the expert's knowledge docs and produces a detailed paragraph
    about what this expert covers and when to consult it.

    Args:
        expert_name: Expert name
        team_name: Team name
        expert_dir: Path to expert's versioned directory (e.g., experts/rich/HEAD/)

    Returns:
        Complete prompt for AI generation
    """
    return f"""\
You are writing a section for a team lead agent definition. The team is "{team_name}".

Read the expert's knowledge documentation at:
- {expert_dir}/summary.md
- {expert_dir}/agent.md
- {expert_dir}/apis_and_interfaces.md
- {expert_dir}/code_structure.md

Then write ONLY the following to stdout (no file writes):

## expert-{expert_name}

[Write a substantial, detailed paragraph (8-15 sentences) describing what this expert covers, \
its core capabilities, key APIs and patterns it knows about, and specific scenarios when the \
orchestrator should consult it. Be concrete — mention actual class names, modules, CLI commands, \
or architectural patterns. This section is used by the team lead to make routing decisions, so \
it needs enough detail to distinguish this expert from others on the team.]

Write ONLY the ## heading and paragraph. No frontmatter, no extra sections.\
"""


def expert_notes_template(expert_name: str, team_name: str) -> str:
    """Template for expert notes stub file.

    Args:
        expert_name: Expert name
        team_name: Team name

    Returns:
        Stub notes.md content with instructions
    """
    return f"""\
# {expert_name} — {team_name} Notes

This file tracks consultations for expert-{expert_name} within the {team_name} team.
Update this file every time you are consulted. Add entries at the top (newest first).

## Format

Each entry should include:
- **Date**: When you were consulted
- **Query**: What main asked you
- **Summary**: Key findings reported back to main

---
"""


def agent_md_template(name: str, commit: str) -> str:
    """Template for agent.md file body (no frontmatter).

    This is the core expert agent definition with strengthened instructions
    that mandate knowledge doc reading and source code verification.

    Args:
        name: Expert name (e.g., "textual")
        commit: Git commit hash for version awareness

    Returns:
        Agent markdown body template with placeholders (no frontmatter)
    """
    return f"""\
# Expert: [Full Repository Name]

[REPLACE THIS WITH ONE PARAGRAPH — no section heading above it. Describe what this repository is, what it does, and list the specific topics/scenarios when this expert should be invoked. This text is extracted verbatim as the agent description. Example: "Expert on the Foo library. Use proactively when questions involve X, Y, Z. Automatically invoked for questions about A, B, C."]

## Knowledge Base

- Summary: {{EXPERTS_DIR}}/{name}/HEAD/summary.md
- Code Structure: {{EXPERTS_DIR}}/{name}/HEAD/code_structure.md
- Build System: {{EXPERTS_DIR}}/{name}/HEAD/build_system.md
- APIs: {{EXPERTS_DIR}}/{name}/HEAD/apis_and_interfaces.md

## Source Access

Repository source at `{{CACHE_DIR}}/repos/{name}`.
If not present, run: `hivemind enable {name}`

**External Documentation:**
Additional crawled documentation may be available at `{{CACHE_DIR}}/external_docs/{name}/`.
These are supplementary markdown files from external sources (not from the repository).
Use these docs when repository knowledge is insufficient or for external API references.

## Instructions

**CRITICAL: You MUST follow this workflow for EVERY question:**

### Before Answering ANY Question:

1. **READ KNOWLEDGE DOCS FIRST** - ALWAYS start by reading relevant files from:
   - `{{EXPERTS_DIR}}/{name}/HEAD/summary.md` - Repository overview
   - `{{EXPERTS_DIR}}/{name}/HEAD/code_structure.md` - Code organization
   - `{{EXPERTS_DIR}}/{name}/HEAD/build_system.md` - Build and dependencies
   - `{{EXPERTS_DIR}}/{name}/HEAD/apis_and_interfaces.md` - APIs and usage patterns

2. **SEARCH SOURCE CODE** - Use Grep and Glob to find relevant code at `{{CACHE_DIR}}/repos/{name}/`:
   - Search for class definitions, function signatures, API patterns
   - Read actual implementation files
   - Verify claims against real code

3. **VERIFY BEFORE CLAIMING** - Never answer from memory alone:
   - If information is in knowledge docs, cite the specific file
   - If information is in source code, provide file paths and line numbers
   - If information is NOT found, explicitly say so

### Response Requirements:

4. **PROVIDE FILE PATHS** - Every answer must include:
   - Specific file paths (e.g., `src/textual/widget.py:145`)
   - Line numbers when referencing code
   - Links to knowledge docs when applicable

5. **INCLUDE CODE EXAMPLES** - Show actual code from the repository:
   - Use real patterns from the codebase
   - Include working examples
   - Reference existing implementations

6. **ACKNOWLEDGE LIMITATIONS** - Be explicit when:
   - Information is not in knowledge docs or source
   - You need to search the repository
   - The answer might be outdated relative to repo version

### Anti-Hallucination Rules:

- NEVER answer from general LLM knowledge about this repository
- NEVER assume API behavior without checking source code
- NEVER skip reading knowledge docs "because you know the answer"
- ALWAYS ground answers in knowledge docs and source code
- ALWAYS search the repository when knowledge docs are insufficient
- ALWAYS cite specific files and line numbers

## Expertise

[Generate detailed list of expertise areas from your analysis]

## Constraints

- **Scope**: Only answer questions directly related to this repository
- **Evidence Required**: All answers must be backed by knowledge docs or source code
- **No Speculation**: If information is not found in knowledge docs or source, say "I need to search the repository" and use Grep/Glob
- **Version Awareness**: Note if information might be outdated (current version: commit {commit})
- **Verification**: When uncertain, read the actual source code at `{{CACHE_DIR}}/repos/{name}/`
- **Hallucination Prevention**: Never provide API details, class signatures, or implementation specifics from memory alone
"""


def create_expert_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for creating a new expert (generates all 5 files).

    Used by `hivemind add` to create a complete expert with knowledge docs
    and agent.md from scratch.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are performing a deep analysis of the repository at {repo_dir} to create expert knowledge documentation for the "{name}" expert.

The commit is {commit}. Write all files into {commit_dir}/.

Generate these 5 files:

1. **{commit_dir}/summary.md** (500-800 words)
   - Repository purpose and goals
   - Key features and capabilities
   - Primary use cases and target audience
   - High-level architecture overview
   - Related projects and dependencies

2. **{commit_dir}/code_structure.md** (1000-1500 words)
   - Complete annotated directory tree
   - Module and package organization
   - Main source directories and their purposes
   - Key files and their roles
   - Code organization patterns

3. **{commit_dir}/build_system.md** (800-1200 words)
   - Build system type and configuration files
   - External dependencies and management
   - Build targets and commands
   - How to build, test, and deploy

4. **{commit_dir}/apis_and_interfaces.md** (1000-1500 words)
   - Public APIs and entry points
   - Key classes, functions, and macros
   - Usage examples with code snippets
   - Integration patterns and workflows
   - Configuration options and extension points

5. **{commit_dir}/agent.md** — Expert subagent definition. Use this exact template, filling in the bracketed sections from your analysis:

```markdown
{agent_md_template(name, commit)}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in agent.md.** The file must start directly with `# Expert:`. Frontmatter is added automatically at deploy time.

Replace the bracketed sections with specific content from your analysis:
- The `[Full Repository Name]` heading should be the actual project name
- The description paragraph MUST come directly after the `# Expert:` heading — do NOT add `## Overview` or any other section heading between them. This paragraph is extracted by parsing the first text block after the h1 heading; any `##` heading will cut off extraction and produce a blank description.
- The `[Generate detailed list...]` in Expertise should be comprehensive (100-150+ lines)

**IMPORTANT for Instructions Section:** The Instructions section MUST be comprehensive and mandate that the expert:
- ALWAYS reads knowledge docs before answering
- ALWAYS searches source code for verification
- NEVER answers from LLM memory alone
- ALWAYS provides file paths and line numbers
- ALWAYS acknowledges when information is not found

Use strong, mandatory language ("MUST", "ALWAYS", "NEVER") in the Instructions section.

Analyze the repository thoroughly using Read, Grep, and Glob tools before writing. Explore the directory structure, key source files, build files, and documentation. Write comprehensive, accurate documentation based on actual code inspection.\
"""


def update_expert_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for updating an expert (regenerates 4 knowledge docs, preserves agent.md).

    Used by `hivemind update` to refresh knowledge documentation while
    preserving custom agent.md configurations.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are analyzing the repository at {repo_dir} to refresh knowledge documentation for the "{name}" expert.

The commit is {commit}. Write updated documentation files into {commit_dir}/.

Regenerate these 4 files (overwrite completely):

1. **{commit_dir}/summary.md** (500-800 words)
   - Repository purpose and goals
   - Key features and capabilities
   - Primary use cases and target audience
   - High-level architecture overview
   - Related projects and dependencies

2. **{commit_dir}/code_structure.md** (1000-1500 words)
   - Complete annotated directory tree
   - Module and package organization
   - Main source directories and their purposes
   - Key files and their roles
   - Code organization patterns

3. **{commit_dir}/build_system.md** (800-1200 words)
   - Build system type and configuration files
   - External dependencies and management
   - Build targets and commands
   - How to build, test, and deploy

4. **{commit_dir}/apis_and_interfaces.md** (1000-1500 words)
   - Public APIs and entry points
   - Key classes, functions, and macros
   - Usage examples with code snippets
   - Integration patterns and workflows
   - Configuration options and extension points

**IMPORTANT:** Do NOT modify {commit_dir}/agent.md — it contains custom agent configuration that must be preserved.

Analyze the repository thoroughly using Read, Grep, and Glob tools before writing. Explore the directory structure, key source files, build files, and documentation. Write comprehensive, accurate documentation based on actual code inspection.\
"""


def regenerate_agent_prompt(
    name: str,
    commit: str,
    repo_dir: Path,
    commit_dir: Path,
) -> str:
    """Prompt for regenerating only agent.md (preserves knowledge docs).

    Used by `scripts/regenerate_agents.py` to update agent.md with template
    changes while preserving existing knowledge documentation.

    Args:
        name: Expert name
        commit: Git commit hash
        repo_dir: Path to cloned repository
        commit_dir: Path to expert's commit directory

    Returns:
        Complete prompt for AI analysis
    """
    return f"""\
You are regenerating ONLY the agent.md file for the "{name}" expert.

The repository is at: {repo_dir}
The commit is: {commit}
The expert directory is: {commit_dir}/

**EXISTING KNOWLEDGE DOCUMENTATION:**
Read these files to understand the repository (DO NOT regenerate them):
- {commit_dir}/summary.md - Repository overview
- {commit_dir}/code_structure.md - Code organization
- {commit_dir}/build_system.md - Build and dependencies
- {commit_dir}/apis_and_interfaces.md - APIs and usage patterns

**YOUR TASK:**
Generate ONLY the file: {commit_dir}/agent.md

Use this exact template, filling in the bracketed sections based on the existing knowledge docs and source code inspection:

```markdown
{agent_md_template(name, commit)}
```

**CRITICAL: Do NOT include YAML frontmatter (---) in agent.md.** The file must start directly with `# Expert:`. Frontmatter is added automatically at deploy time.

**IMPORTANT:**
1. Read the existing knowledge docs first to extract repository details
2. Generate ONLY the agent.md file - do NOT regenerate the knowledge docs
3. Fill in the [bracketed sections] with specific content from the knowledge docs
4. The description paragraph after the heading should list concrete topics and scenarios
5. The Expertise section should be comprehensive (100-150+ lines) based on knowledge docs\
"""
